// // Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// // for details. All rights reserved. Use of this source code is governed by a
// // BSD-style license that can be found in the LICENSE file.
//
// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//
//
//
//     // TODO(Lyokone): Remove when FlutterFire CLI updated
//       case TargetPlatform.windows:
//         return android;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAUpgyQ4gYEtxC9biTk4FXAX7TTs_G8S28',
//     appId: '1:841898291150:android:8707bf6fb570c8feea859f',
//     messagingSenderId: '406099696497',
//     projectId: 'plant-store-f0b97',
//
//
//     storageBucket: 'plant-store-f0b97.appspot.com',
//   );
//
//
//
//
//
//
// }